---
title: "Exceptions: The failwith Function (F#)"
ms.custom: na
ms.date: 09/19/2016
ms.devlang: 
  - FSharp
ms.prod: visual-studio-dev14
ms.reviewer: na
ms.suite: na
ms.technology: 
  - devlang-fsharp
ms.tgt_pltfrm: na
ms.topic: reference
ms.assetid: b976178b-4e3f-4c51-8212-c4969818966f
caps.latest.revision: 17
translation.priority.ht: 
  - de-de
  - ja-jp
---
# Exceptions: The failwith Function (F#)
The `failwith` function generates an F# exception.  
  
## Syntax  
  
```  
failwith error-message-string  
```  
  
## Remarks  
 The `error-message-string` in the previous syntax is a literal string or a value of type `string`. It becomes the `Message` property of the exception.  
  
 The exception that is generated by `failwith` is a `Microsoft.FSharp.Core.FailureException` exception, which is a reference that has the name `Failure` in F# code. The following code illustrates the use of `failwith` to throw an exception.  
  
 [!CODE [FsLangRef2#6001](../CodeSnippet/VS_Snippets_Fsharp/fslangref2#6001)]  
  
## See Also  
 [Exception Handling (F#)](../vs140/Exception-Handling--F#-.md)   
 [Exception Types](../Topic/Exception%20Types%20\(F%23\).md)   
 [Exceptions: the try .. with Expression](../vs140/Exceptions--The-try...with-Expression--F#-.md)   
 [Exceptions: the try .. finally Expression](../vs140/Exceptions--The-try...finally-Expression--F#-.md)   
 [Exceptions: the raise Function](../vs140/Exceptions--the-raise-Function--F#-.md)